version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      -  .:/src
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '8080:8080'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge