version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network


  backend-app:
    image: yolo_backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      -  .:/src
    networks:
      - node-network

  client-app:
  
    image: yolo_client 
    ports:
      - '3000:3000'
    volumes:
      -  .:/src
    networks:
      - node-network

  
volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge