apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo-backend
          image: munjirue/yolo-backend_img:v1.0.0.1
          env:
            - name: MONGODB_URI
              value: mongodb://yolo-db:27017/yolomy
          ports:
            - containerPort: 5000